"""Add looks block columns to sprite

Revision ID: a826f4c651cc
Revises: 
Create Date: 2025-12-04 11:23:10.566558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a826f4c651cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broadcast_messages_id', table_name='broadcast_messages')
    op.drop_table('broadcast_messages')
    op.drop_index('ix_sounds_id', table_name='sounds')
    op.drop_table('sounds')
    op.drop_index('ix_keyboard_states_id', table_name='keyboard_states')
    op.drop_table('keyboard_states')
    op.drop_index('ix_event_logs_id', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_sensor_readings_id', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('ix_event_bindings_id', table_name='event_bindings')
    op.drop_table('event_bindings')
    op.drop_index('ix_timer_states_id', table_name='timer_states')
    op.drop_table('timer_states')
    op.add_column('sprites', sa.Column('graphic_effects', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprites', 'graphic_effects')
    op.create_table('timer_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_running', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='timer_states_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='timer_states_pkey'),
    sa.UniqueConstraint('project_id', name='timer_states_project_id_key')
    )
    op.create_index('ix_timer_states_id', 'timer_states', ['id'], unique=False)
    op.create_table('event_bindings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sprite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('handler_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('script_blocks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('execution_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='event_bindings_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], name='event_bindings_sprite_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_bindings_pkey')
    )
    op.create_index('ix_event_bindings_id', 'event_bindings', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sprite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sensor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='sensor_readings_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], name='sensor_readings_sprite_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sensor_readings_pkey')
    )
    op.create_index('ix_sensor_readings_id', 'sensor_readings', ['id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sprite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('handlers_executed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='event_logs_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], name='event_logs_sprite_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='event_logs_pkey')
    )
    op.create_index('ix_event_logs_id', 'event_logs', ['id'], unique=False)
    op.create_table('keyboard_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pressed_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_key', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_press_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='keyboard_states_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='keyboard_states_pkey'),
    sa.UniqueConstraint('project_id', name='keyboard_states_project_id_key')
    )
    op.create_index('ix_keyboard_states_id', 'keyboard_states', ['id'], unique=False)
    op.create_table('sounds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sprite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('audio_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bit_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sound_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='sounds_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], name='sounds_sprite_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sounds_pkey')
    )
    op.create_index('ix_sounds_id', 'sounds', ['id'], unique=False)
    op.create_table('broadcast_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='broadcast_messages_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='broadcast_messages_pkey')
    )
    op.create_index('ix_broadcast_messages_id', 'broadcast_messages', ['id'], unique=False)
    # ### end Alembic commands ###
